### ISSUE TITLE
Links to hardware in README

### ISSUE THREAD

**Issue by tobru** [bliemli/home-assistant-config#1]
Yay, great things going on here! :tada: Would be great to have some links to the hardware used in the README, and maybe some hints where to buy it.

**Comment by bliemli** [comment]
Fixed by https://github.com/bliemli/home-assistant-config/commit/6864620c9b1dbeb30b17fa2f1f4a6e2cab5f54ff. I left out hints on where to buy the mentioned devices as I don't want to favor any specific store or shop.
